const suppliersCiudad = [
    {"city": "Bogotá"}, 
    {"city": "Medellín"}, 
    {"city": "Cali"}, 
    {"city": "Barranquilla"}, 
    {"city": "Cartagena"}, 
    {"city": "Soacha"}, 
    {"city": "Palermo"}, 
    {"city": "Cúcuta"}, 
    {"city": "Soledad"}, 
    {"city": "Pereira"}, 
    {"city": "Bucaramanga"}, 
    {"city": "Valledupar"}, 
    {"city": "Ibagué"}, 
    {"city": "Villavicencio"}, 
    {"city": "Santa Marta"}, 
    {"city": "Montería"}, 
    {"city": "Manizales"}, 
    {"city": "Buenaventura"}, 
    {"city": "Pasto"}, 
    {"city": "Bello"}, 
    {"city": "Neiva"}, 
    {"city": "Armenia"}, 
    {"city": "Popayán"}, 
    {"city": "Sincelejo"}, 
    {"city": "Floridablanca"}, 
    {"city": "Itagüí"}, 
    {"city": "Envigado"}, 
    {"city": "Tuluá"}, 
    {"city": "Tumaco"}, 
    {"city": "Barrancabermeja"}, 
    {"city": "Tunja"}, 
    {"city": "Zipaquirá"}, 
    {"city": "Turbo"}, 
    {"city": "Yopal"}, 
    {"city": "Dosquebradas"}, 
    {"city": "Ríohacha"}, 
    {"city": "Girón"}, 
    {"city": "Florencia"}, 
    {"city": "Fusagasugá"}, 
    {"city": "Cartago"}, 
    {"city": "Pitalito"}, 
    {"city": "Ciénaga"}, 
    {"city": "Sogamoso"}, 
    {"city": "Quibdó"}, 
    {"city": "Girardot"}, 
    {"city": "Duitama"}, 
    {"city": "Magangué"}, 
    {"city": "Maicao"}, 
    {"city": "Uribia"}, 
    {"city": "Piedecuesta"}, 
    {"city": "Facatativá"}, 
    {"city": "Guadalajara de Buga"}, 
    {"city": "Madrid"}, 
    {"city": "Santander de Quilichao"}, 
    {"city": "Aguachica"}, 
    {"city": "Ipiales"}, 
    {"city": "Chía"}, 
    {"city": "Jamundí"}, 
    {"city": "Arauca"}, 
    {"city": "Yumbo"}, 
    {"city": "Mosquera"}, 
    {"city": "Fundación"}, 
    {"city": "Ocaña"}, 
    {"city": "Montelíbano"}, 
    {"city": "Chiquinquirá"}, 
    {"city": "Sabanalarga"}, 
    {"city": "Chigorodó"}, 
    {"city": "Cereté"}, 
    {"city": "Caldas"}, 
    {"city": "Funza"}, 
    {"city": "Los Patios"}, 
    {"city": "Tierralta"}, 
    {"city": "El Carmen de Bolívar"}, 
    {"city": "La Dorada"}, 
    {"city": "Arjona"}, 
    {"city": "Turbaco"}, 
    {"city": "Espinal"}, 
    {"city": "Acacías"}, 
    {"city": "Copacabana"}, 
    {"city": "Santa Rosa de Cabal"}, 
    {"city": "San Vicente del Caguán"}, 
    {"city": "San Andrés"}, 
    {"city": "Corozal"}, 
    {"city": "Villa del Rosario"}, 
    {"city": "Garzón"}, 
    {"city": "Planeta Rica"}, 
    {"city": "Necoclí"}, 
    {"city": "San José del Guaviare"}, 
    {"city": "Manaure"}, 
    {"city": "Marinilla"}, 
    {"city": "Ciénaga de Oro"}, 
    {"city": "Puerto Asís"}, 
    {"city": "Riosucio"}, 
    {"city": "Plato"}, 
    {"city": "Carepa"}, 
    {"city": "Cajicá"}, 
    {"city": "Villamaría"}, 
    {"city": "San Marcos"}, 
    {"city": "Girardota"}, 
    {"city": "Florida"}, 
    {"city": "Pamplona"}, 
    {"city": "Pradera"}, 
    {"city": "Orito"}, 
    {"city": "Puerto Boyacá"}, 
    {"city": "El Banco"}, 
    {"city": "San Gil"}, 
    {"city": "Sabaneta"}, 
    {"city": "Valle del Guamuez"}, 
    {"city": "Puerto Libertador"}, 
    {"city": "Tame"}, 
    {"city": "Barbosa"}, 
    {"city": "Lorica"}, 
    {"city": "San Onofre"}, 
    {"city": "Guarne"}, 
    {"city": "El Bagre"}, 
    {"city": "Chinú"}, 
    {"city": "Baranoa"}, 
    {"city": "Puerto Berrío"}, 
    {"city": "Cimitarra"}, 
    {"city": "María la Baja"}, 
    {"city": "Agustín Codazzi"}, 
    {"city": "Samaniego"}, 
    {"city": "Carmen de Viboral"}, 
    {"city": "Yarumal"}, 
    {"city": "La Vega"}, 
    {"city": "Chaparral"}, 
    {"city": "Andes"}, 
    {"city": "San Andrés de Sotavento"}, 
    {"city": "Ayapel"}, 
    {"city": "Urrao"}, 
    {"city": "Zarzal"}, 
    {"city": "Valencia"}, 
    {"city": "Roldanillo"}, 
    {"city": "Puerto Tejada"}, 
    {"city": "Santa Rosa del Sur"}, 
    {"city": "San Pelayo"}, 
    {"city": "Arboletes"}, 
    {"city": "Villeta"}, 
    {"city": "Aguazul"}, 
    {"city": "Cumaribo"}, 
    {"city": "Miranda"}, 
    {"city": "El Charco"}, 
    {"city": "Cáceres"}, 
    {"city": "Montenegro"}, 
    {"city": "Pueblo Nuevo"}, 
    {"city": "Tuchín"}, 
    {"city": "Arauquita"}, 
    {"city": "Guaduas"}, 
    {"city": "Pie de Pató"}, 
    {"city": "Cumbal"}, 
    {"city": "Aracataca"}, 
    {"city": "La Unión"}, 
    {"city": "Túquerres"}, 
    {"city": "Acevedo"}, 
    {"city": "Bosconia"}, 
    {"city": "Líbano"}, 
    {"city": "Villa de San Diego de Ubaté"}, 
    {"city": "San Juan del Cesar"}, 
    {"city": "Tarazá"}, 
    {"city": "Cajibío"}, 
    {"city": "Segovia"}, 
    {"city": "Sibaté"}, 
    {"city": "Sampués"}, 
    {"city": "Dibulla"}, 
    {"city": "El Bordo"}, 
    {"city": "Santa Rosa de Osos"}, 
    {"city": "Tibú"}, 
    {"city": "Melgar"}, 
    {"city": "Dagua"}, 
    {"city": "La Macarena"}, 
    {"city": "Belalcázar"}, 
    {"city": "Sonsón"}, 
    {"city": "San Pablo"}, 
    {"city": "San Bernardo del Viento"}, 
    {"city": "Santiago de Tolú"}, 
    {"city": "Guacarí"}, 
    {"city": "Timbío"}, 
    {"city": "Gigante"}, 
    {"city": "Cartagena del Chairá"}, 
    {"city": "Tocancipá"}, 
    {"city": "Yarumal"}, 
    {"city": "Quimbaya"}, 
    {"city": "Fonseca"}, 
    {"city": "San Vicente de Chucurí"}, 
    {"city": "Puerto López"}, 
    {"city": "San Luis de Sincé"}, 
    {"city": "Campoalegre"}, 
    {"city": "Sabanagrande"}, 
    {"city": "Caldono"}, 
    {"city": "San Agustín"}, 
    {"city": "San Juan Nepomuceno"}, 
    {"city": "Majagual"}, 
    {"city": "Quinchía"}, 
    {"city": "Puerto Rico"}, 
    {"city": "San Antero"}, 
    {"city": "Corinto"}, 
    {"city": "Pivijay"}, 
    {"city": "Puebloviejo"}, 
    {"city": "Bocas de Satinga"}, 
    {"city": "Puerto Escondido"}, 
    {"city": "Silvia"}, 
    {"city": "El Difícil"}, 
    {"city": "Inzá"}, 
    {"city": "Leticia"}, 
    {"city": "La Virginia"}, 
    {"city": "San Pedro de Urabá"}, 
    {"city": "Remedios"}, 
    {"city": "Paipa"}, 
    {"city": "Guachavés"}, 
    {"city": "Sitionuevo"}, 
    {"city": "Puerto Wilches"}, 
    {"city": "Neira"}, 
    {"city": "Guamo"}, 
    {"city": "Circasia"}, 
    {"city": "Amagá"}, 
    {"city": "Chimichagua"}, 
    {"city": "Planadas"}, 
    {"city": "Fresno"}, 
    {"city": "Purificación"}, 
    {"city": "Tabio"}, 
    {"city": "Barbosa"}, 
    {"city": "Flandes"}, 
    {"city": "Aipe"}, 
    {"city": "Sopó"}, 
    {"city": "Moñitos"}, 
    {"city": "Riosucio"}, 
    {"city": "La Dorada"}, 
    {"city": "La Calera"}, 
    {"city": "Caicedonia"}, 
    {"city": "Hatonuevo"}, 
    {"city": "San Carlos"}, 
    {"city": "Isnos"}, 
    {"city": "Coyaima"}, 
    {"city": "Mitú"}, 
    {"city": "Guamal"}, 
    {"city": "Luruaco"}, 
    {"city": "Belén de Umbría"}, 
    {"city": "Argelia"}, 
    {"city": "Supía"}, 
    {"city": "Ciudad Bolívar"}, 
    {"city": "Repelón"}, 
    {"city": "San Juan de Urabá"}, 
    {"city": "Puerto Colombia"}, 
    {"city": "Fortul"}, 
    {"city": "Morales"}, 
    {"city": "Los Córdobas"}, 
    {"city": "San Benito Abad"}, 
    {"city": "San Alberto"}, 
    {"city": "Balboa"}, 
    {"city": "Pensilvania"}, 
    {"city": "Paz de Ariporo"}, 
    {"city": "Buesaco"}, 
    {"city": "Istmina"}, 
    {"city": "Santa Ana"}, 
    {"city": "San Martín"}, 
    {"city": "Palmar de Varela"}, 
    {"city": "Nechí"}, 
    {"city": "Yolombó"}, 
    {"city": "Solano"}, 
    {"city": "Vistahermosa"}, 
    {"city": "San José"}, 
    {"city": "La Unión"}, 
    {"city": "Chocontá"}, 
    {"city": "Sandoná"}, 
    {"city": "Pinillos"}, 
    {"city": "Socorro"}, 
    {"city": "Tauramena"}, 
    {"city": "Villanueva"}, 
    {"city": "Algeciras"}, 
    {"city": "Santa Rosa"}, 
    {"city": "Pueblo Bello"}, 
    {"city": "El Retorno"}, 
    {"city": "Valdivia"}, 
    {"city": "Puerto Guzmán"}, 
    {"city": "La Montañita"}, 
    {"city": "Donmatías"}, 
    {"city": "Rioblanco"}, 
    {"city": "Marsella"}, 
    {"city": "Cogua"}, 
    {"city": "El Zulia"}, 
    {"city": "Honda"}, 
    {"city": "El Paso"}, 
    {"city": "Canalete"}, 
    {"city": "Teorama"}, 
    {"city": "San José"}, 
    {"city": "Ponedera"}, 
    {"city": "Alcalá"}, 
    {"city": "Puerto Concordia"}, 
    {"city": "Achí"}, 
    {"city": "Curumaní"}, 
    {"city": "Dabeiba"}, 
    {"city": "Guadalupe"}, 
    {"city": "Ataco"}, 
    {"city": "Santa Fe de Antioquia"}, 
    {"city": "Amalfi"}, 
    {"city": "Buenavista"}, 
    {"city": "Manzanares"}, 
    {"city": "Sardinata"}, 
    {"city": "Mutatá"}, 
    {"city": "La Jagua de Ibirico"}, 
    {"city": "Natagaima"}, 
    {"city": "El Doncello"}, 
    {"city": "El Colegio"}, 
    {"city": "Pailitas"}, 
    {"city": "Timbiquí"}, 
    {"city": "Tiquisio"}, 
    {"city": "Mocoa"}, 
    {"city": "Silvania"}, 
    {"city": "Taminango"}, 
    {"city": "Ginebra"}, 
    {"city": "Puerto Triunfo"}, 
    {"city": "San Jacinto"}, 
    {"city": "Nueva Granada"}, 
    {"city": "Galeras"}, 
    {"city": "Villagarzón"}, 
    {"city": "San Bernardo"}, 
    {"city": "El Paujíl"}, 
    {"city": "Santa Bárbara"}, 
    {"city": "Moniquirá"}, 
    {"city": "Almaguer"}, 
    {"city": "Totoró"}, 
    {"city": "Aguadas"}, 
    {"city": "Montecristo"}, 
    {"city": "Suaza"}, 
    {"city": "Villapinzón"}, 
    {"city": "Fredonia"}, 
    {"city": "El Retén"}, 
    {"city": "Bugalagrande"}, 
    {"city": "López"}, 
    {"city": "Sotomayor"}, 
    {"city": "Ovejas"}, 
    {"city": "Samacá"}, 
    {"city": "Timaná"}, 
    {"city": "San Lorenzo"}, 
    {"city": "Concordia"}, 
    {"city": "Simití"}, 
    {"city": "Tenjo"}, 
    {"city": "Rovira"}, 
    {"city": "Inírida"}, 
    {"city": "Urumita"}, 
    {"city": "Polonuevo"}, 
    {"city": "La Unión"}, 
    {"city": "Tadó"}, 
    {"city": "Vélez"}, 
    {"city": "Tocaima"}, 
    {"city": "Villa de Leyva"}, 
    {"city": "Campo de la Cruz"}, 
    {"city": "Sabana de Torres"}, 
    {"city": "Pelaya"}, 
    {"city": "Salgar"}, 
    {"city": "La Primavera"}, 
    {"city": "Guaranda"}, 
    {"city": "Suesca"}, 
    {"city": "Betulia"}, 
    {"city": "El Rosal"}, 
    {"city": "Retiro"}, 
    {"city": "Puerto Carreño"}, 
    {"city": "El Piñón"}, 
    {"city": "Anorí"}, 
    {"city": "Aquitania"}, 
    {"city": "Chivolo"}, 
    {"city": "Guasca"}, 
    {"city": "Landázuri"}, 
    {"city": "Támesis"}, 
    {"city": "Obando"}, 
    {"city": "Condoto"}, 
    {"city": "Sopetrán"}, 
    {"city": "Tenerife"}, 
    {"city": "Juan de Acosta"}, 
    {"city": "Titiribí"}, 
    {"city": "El Carmen de Atrato"}, 
    {"city": "Río de Oro"}, 
    {"city": "Córdoba"}, 
    {"city": "Guapí"}, 
    {"city": "Jardín"}, 
    {"city": "Altos del Rosario"}, 
    {"city": "Filandia"}, 
    {"city": "Manatí"}, 
    {"city": "San Jacinto del Cauca"}, 
    {"city": "Rosas"}, 
    {"city": "Anolaima"}, 
    {"city": "Los Santos"}, 
    {"city": "Santa Bárbara de Pinto"}, 
    {"city": "Candelaria"}, 
    {"city": "Saboyá"}, 
    {"city": "Hatillo de Loba"}, 
    {"city": "Córdoba"}, 
    {"city": "Ebéjico"}, 
    {"city": "Caimito"}, 
    {"city": "Curití"}, 
    {"city": "Oiba"}, 
    {"city": "Santa Lucía"}, 
    {"city": "Puente Nacional"}, 
    {"city": "La Unión"}, 
    {"city": "Cisneros"}, 
    {"city": "Guayabal"}, 
    {"city": "Talaigua Nuevo"}, 
    {"city": "Coveñas"}, 
    {"city": "Bojacá"}, 
    {"city": "El Playón"}, 
    {"city": "El Águila"}, 
    {"city": "Agua de Dios"}, 
    {"city": "El Tarra"}, 
    {"city": "Mogotes"}, 
    {"city": "Santo Domingo"}, 
    {"city": "Tubará"}, 
    {"city": "Regidor"}, 
    {"city": "Lenguazaque"}, 
    {"city": "Charalá"}, 
    {"city": "Medina"}, 
    {"city": "Granada"}, 
    {"city": "Suaita"}, 
    {"city": "Margarita"}, 
    {"city": "Norosí"}, 
    {"city": "Chita"}, 
    {"city": "Pesca"}, 
    {"city": "Granada"}, 
    {"city": "Tibaná"}, 
    {"city": "San Zenón"}, 
    {"city": "Nuquí"}, 
    {"city": "Alvarado"}, 
    {"city": "Zapatoca"}, 
    {"city": "Junín"}, 
    {"city": "Iles"}, 
    {"city": "La Belleza"}, 
    {"city": "Usiacurí"}, 
    {"city": "Muzo"}, 
    {"city": "Orocué"}, 
    {"city": "Guatapé"}, 
    {"city": "San Francisco"}, 
    {"city": "Aratoca"}, 
    {"city": "Uramita"}, 
    {"city": "Uribe"}, 
    {"city": "Motavita"}, 
    {"city": "Pedraza"}, 
    {"city": "Puerto Parra"}, 
    {"city": "San Luis de Palenque"}, 
    {"city": "Paratebueno"}, 
    {"city": "Santana"}, 
    {"city": "Coromoro"}, 
    {"city": "Ambalema"}, 
    {"city": "Tarso"}, 
    {"city": "Maripí"}, 
    {"city": "Simacota"}, 
    {"city": "Soatá"}, 
    {"city": "Tona"}, 
    {"city": "Socha"}, 
    {"city": "Salento"}, 
    {"city": "Boavita"}, 
    {"city": "Guatavita"}, 
    {"city": "Güicán"}, 
    {"city": "Puerto Nariño"}, 
    {"city": "Cubará"}, 
    {"city": "Tasco"}, 
    {"city": "Florián"}, 
    {"city": "Heliconia"}, 
    {"city": "Colosó"}, 
    {"city": "Albán"}, 
    {"city": "Sutamarchán"}, 
    {"city": "Chitaraque"}, 
    {"city": "Zipacón"}, 
    {"city": "Chíquiza"}, 
    {"city": "Villanueva"}, 
    {"city": "Caramanta"}, 
    {"city": "Tota"}, 
    {"city": "Córdoba"}, 
    {"city": "El Cocuy"}, 
    {"city": "Arcabuco"}, 
    {"city": "San José de Pare"}, 
    {"city": "Labranzagrande"}, 
    {"city": "Togüí"}, 
    {"city": "Piojó"}, 
    {"city": "El Peñón"}, 
    {"city": "Chiscas"}, 
    {"city": "Santa Rosalía"}, 
    {"city": "El Espino"}, 
    {"city": "Puerto Rondón"}, 
    {"city": "Sáchica"}, 
    {"city": "Güepsa"}, 
    {"city": "San Mateo"}, 
    {"city": "Guavatá"}, 
    {"city": "Guayabal de Síquima"}, 
    {"city": "Chinavita"}, 
    {"city": "Concepción"}, 
    {"city": "La Jagua del Pilar"}, 
    {"city": "Cravo Norte"}, 
    {"city": "Palmar"}, 
    {"city": "Tipacoque"}, 
    {"city": "Susacón"}, 
    {"city": "Tinjacá"}, 
    {"city": "Sora"}, 
    {"city": "Covarachía"}, 
    {"city": "Oicatá"}, 
    {"city": "Guataquí"}, 
    {"city": "Santa Sofía"}, 
    {"city": "Jerusalén"}, 
    {"city": "Gachantivá"}, 
    {"city": "Briceño"}, 
    {"city": "La Uvita"}, 
    {"city": "Encino"}, 
    {"city": "Vetas"}, 
    {"city": "Juradó"}, 
    {"city": "Iza"}, 
    {"city": "Sativanorte"}, 
    {"city": "Palmas del Socorro"}, 
    {"city": "Almeida"}, 
    {"city": "Guacamayas"}, 
    {"city": "Galán"}, 
    {"city": "Tutazá"}, 
    {"city": "Cepitá"}, 
    {"city": "San Eduardo"}, 
    {"city": "Tununguá"}, 
    {"city": "Pajarito"}, 
    {"city": "La Victoria"}, 
    {"city": "Panqueba"}, 
    {"city": "Sativasur"}, 
    {"city": "Mahates"}, 
    {"city": "Barichara"}, 
    {"city": "La Estrella"}, 
    {"city": "Malambo"}, 
    {"city": "Rionegro"}, 
    {"city": "Galapa"}, 
    {"city": "Cota"}, 
    {"city": "La Tebaida"}, 
    {"city": "Chinchiná"}, 
    {"city": "Gachancipá"}, 
    {"city": "La Ceja"}, 
    {"city": "Santuario"}, 
    {"city": "Calarcá"}, 
    {"city": "Sesquilé"}, 
    {"city": "Santo Tomás"}, 
    {"city": "Nobsa"}, 
    {"city": "Málaga"}, 
    {"city": "Palmira"}, 
    {"city": "Providencia"}, 
    {"city": "Candelaria"}, 
    {"city": "Apartadó"}, 
    {"city": "Guateque"}, 
    {"city": "Piendamó"}, 
    {"city": "Sahagún"}, 
    {"city": "Marmato"}, 
    {"city": "Suan"}, 
    {"city": "Santa Isabel"}, 
    {"city": "La Mesa"}, 
    {"city": "Villa Rica"}, 
    {"city": "Puerto Santander"}, 
    {"city": "Granada"}, 
    {"city": "Sibundoy"}, 
    {"city": "Cotorra"}, 
    {"city": "Cachipay"}, 
    {"city": "Gualmatán"}, 
    {"city": "Buenos Aires"}, 
    {"city": "Belén"}, 
    {"city": "Recetor"}, 
    {"city": "Coello"}, 
    {"city": "Tena"}, 
    {"city": "Tibasosa"}, 
    {"city": "Génova"}, 
    {"city": "Marquetalia"}, 
    {"city": "Peñol"}, 
    {"city": "San Pablo"}, 
    {"city": "Guática"}, 
    {"city": "Clemencia"}, 
    {"city": "Contadero"}, 
    {"city": "Nilo"}, 
    {"city": "La Pintada"}, 
    {"city": "Pupiales"}, 
    {"city": "Susa"}, 
    {"city": "Ulloa"}, 
    {"city": "Villanueva"}, 
    {"city": "Cicuco"}, 
    {"city": "San Cristóbal"}, 
    {"city": "San Antonio del Tequendama"}, 
    {"city": "Andalucía"}, 
    {"city": "Anserma"}, 
    {"city": "Prado-Sevilla"}, 
    {"city": "Palocabildo"}, 
    {"city": "Cáqueza"}, 
    {"city": "Cabrera"}, 
    {"city": "Cartago"}, 
    {"city": "Ospina"}, 
    {"city": "Nemocón"}, 
    {"city": "Simijaca"}, 
    {"city": "El Cerrito"}, 
    {"city": "Carlosama"}, 
    {"city": "Aldana"}, 
    {"city": "Nuevo Colón"}, 
    {"city": "Nimaima"}, 
    {"city": "Palestina"}, 
    {"city": "Berruecos"}, 
    {"city": "Apía"}, 
    {"city": "Pueblorrico"}, 
    {"city": "Purísima de la Concepción"}, 
    {"city": "Chivatá"}, 
    {"city": "San Sebastián de Mariquita"}, 
    {"city": "Restrepo"}, 
    {"city": "San Pedro"}, 
    {"city": "Calamar"}, 
    {"city": "Jenesano"}, 
    {"city": "Florencia"}, 
    {"city": "Anapoima"}, 
    {"city": "San José"}, 
    {"city": "Tópaga"}, 
    {"city": "Venecia"}, 
    {"city": "Cucaita"}, 
    {"city": "Angelópolis"}, 
    {"city": "Santa Rosa de Viterbo"}, 
    {"city": "Padilla"}, 
    {"city": "Sutatenza"}, 
    {"city": "Momil"}, 
    {"city": "Risaralda"}, 
    {"city": "Ventaquemada"}, 
    {"city": "Caloto"}, 
    {"city": "Guachené"}, 
    {"city": "Yacuanquer"}, 
    {"city": "San Vicente"}, 
    {"city": "Manaure Balcón del Cesar"}, 
    {"city": "Pinchote"}, 
    {"city": "Turbaná"}, 
    {"city": "Hispania"}, 
    {"city": "Nariño"}, 
    {"city": "Chinácota"}, 
    {"city": "Villanueva"}, 
    {"city": "Vijes"}, 
    {"city": "Cómbita"}, 
    {"city": "Boyacá"}, 
    {"city": "Concordia"}, 
    {"city": "Chachagüí"}, 
    {"city": "Viterbo"}, 
    {"city": "Soplaviento"}, 
    {"city": "Guachucal"}, 
    {"city": "Soracá"}, 
    {"city": "La Vega"}, 
    {"city": "San Pedro"}, 
    {"city": "Mompós"}, 
    {"city": "Belalcázar"}, 
    {"city": "Ciénega"}, 
    {"city": "Oporapa"}, 
    {"city": "Sasaima"}, 
    {"city": "Santa Catalina"}, 
    {"city": "La Hormiga"}, 
    {"city": "Garagoa"}, 
    {"city": "Jambaló"}, 
    {"city": "Tenza"}, 
    {"city": "Nocaima"}, 
    {"city": "Toro"}, 
    {"city": "Los Palmitos"}, 
    {"city": "Palmito"}, 
    {"city": "Subachoque"}, 
    {"city": "La Celia"}, 
    {"city": "Morroa"}, 
    {"city": "San Jerónimo"}, 
    {"city": "Ancuya"}, 
    {"city": "Buenavista"}, 
    {"city": "Consacá"}, 
    {"city": "Imués"}, 
    {"city": "San Pedro"}, 
    {"city": "Sutatausa"}, 
    {"city": "Cocorná"}, 
    {"city": "González"}, 
    {"city": "La Cruz"}, 
    {"city": "Ricaurte"}, 
    {"city": "Lebrija"}, 
    {"city": "Monguí"}, 
    {"city": "Sevilla"}, 
    {"city": "Enciso"}, 
    {"city": "San Juan de Betulia"}, 
    {"city": "Ragonvalia"}, 
    {"city": "San Estanislao"}, 
    {"city": "Santuario"}, 
    {"city": "Ramiriquí"}, 
    {"city": "Caucasia"}, 
    {"city": "Pital"}, 
    {"city": "Saldaña"}, 
    {"city": "Guaitarilla"}, 
    {"city": "Jericó"}, 
    {"city": "Pandi"}, 
    {"city": "Úmbita"}, 
    {"city": "Aranzazu"}, 
    {"city": "Palestina"}, 
    {"city": "Betania"}, 
    {"city": "Fúquene"}, 
    {"city": "Guachetá"}, 
    {"city": "Apulo"}, 
    {"city": "Saravena"}, 
    {"city": "Capitanejo"}, 
    {"city": "Turmequé"}, 
    {"city": "Toribío"}, 
    {"city": "Lérida"}, 
    {"city": "Ráquira"}, 
    {"city": "Sucre"}, 
    {"city": "Linares"}, 
    {"city": "Tolú Viejo"}, 
    {"city": "Ocamonte"}, 
    {"city": "La Florida"}, 
    {"city": "Arroyohondo"}, 
    {"city": "Pacho"}, 
    {"city": "Siachoque"}, 
    {"city": "Distracción"}, 
    {"city": "Fosca"}, 
    {"city": "Toca"}, 
    {"city": "Buenavista"}, 
    {"city": "Cerro de San Antonio"}, 
    {"city": "Venadillo"}, 
    {"city": "Guadalupe"}, 
    {"city": "Tuta"}, 
    {"city": "La Apartada"}, 
    {"city": "Somondoco"}, 
    {"city": "San Pablo de Borbur"}, 
    {"city": "Páramo"}, 
    {"city": "Útica"}, 
    {"city": "Valparaíso"}, 
    {"city": "Ubaque"}, 
    {"city": "Rivera"}, 
    {"city": "Nariño"}, 
    {"city": "La Plata"}, 
    {"city": "Viotá"}, 
    {"city": "Chipatá"}, 
    {"city": "Chipaque"}, 
    {"city": "Filadelfia"}, 
    {"city": "Cucunubá"}, 
    {"city": "Vianí"}, 
    {"city": "Cerinza"}, 
    {"city": "Campamento"}, 
    {"city": "Sapuyes"}, 
    {"city": "Icononzo"}, 
    {"city": "Ansermanuevo"}, 
    {"city": "Cuítiva"}, 
    {"city": "Firavitoba"}, 
    {"city": "La Peña"}, 
    {"city": "Quetame"}, 
    {"city": "Barranco de Loba"}, 
    {"city": "Armenia"}, 
    {"city": "San José de Miranda"}, 
    {"city": "Argelia"}, 
    {"city": "Cañasgordas"}, 
    {"city": "Toledo"}, 
    {"city": "Gamarra"}, 
    {"city": "Trujillo"}, 
    {"city": "Carmen de Apicalá"}, 
    {"city": "Bolívar"}, 
    {"city": "El Roble"}, 
    {"city": "Cumbitara"}, 
    {"city": "Anzoátegui"}, 
    {"city": "La Victoria"}, 
    {"city": "Quebradanegra"}, 
    {"city": "Floresta"}, 
    {"city": "Buenavista"}, 
    {"city": "Balboa"}, 
    {"city": "Albania"}, 
    {"city": "Liborina"}, 
    {"city": "Arbeláez"}, 
    {"city": "Ánimas"}, 
    {"city": "Choachí"}, 
    {"city": "San Fernando"}, 
    {"city": "Quipile"}, 
    {"city": "San Luis"}, 
    {"city": "La Sierra"}, 
    {"city": "Yotoco"}, 
    {"city": "Viracachá"}, 
    {"city": "Tarqui"}, 
    {"city": "San Roque"}, 
    {"city": "Falan"}, 
    {"city": "La Merced"}, 
    {"city": "Barrancas"}, 
    {"city": "Riofrío"}, 
    {"city": "Chimá"}, 
    {"city": "Entrerríos"}, 
    {"city": "Argelia"}, 
    {"city": "Pasca"}, 
    {"city": "California"}, 
    {"city": "Tibacuy"}, 
    {"city": "Salamina"}, 
    {"city": "Chalán"}, 
    {"city": "Nátaga"}, 
    {"city": "San Benito"}, 
    {"city": "Pácora"}, 
    {"city": "Tausa"}, 
    {"city": "Elías"}, 
    {"city": "Abejorral"}, 
    {"city": "Caicedo"}, 
    {"city": "Matanza"}, 
    {"city": "Angostura"}, 
    {"city": "Arenal"}, 
    {"city": "San Rafael"}, 
    {"city": "Leiva"}, 
    {"city": "La Cumbre"}, 
    {"city": "El Cairo"}, 
    {"city": "Valle de San José"}, 
    {"city": "Une"}, 
    {"city": "Gachetá"}, 
    {"city": "Busbanzá"}, 
    {"city": "San Francisco"}, 
    {"city": "Salamina"}, 
    {"city": "Pauna"}, 
    {"city": "El Tablón"}, 
    {"city": "Albania"}, 
    {"city": "Tibirita"}, 
    {"city": "San Sebastián de Buenavista"}, 
    {"city": "La Capilla"}, 
    {"city": "Olaya"}, 
    {"city": "El Tambo"}, 
    {"city": "El Peñol"}, 
    {"city": "Casabianca"}, 
    {"city": "La Argentina"}, 
    {"city": "Quípama"}, 
    {"city": "San Cayetano"}, 
    {"city": "Belén"}, 
    {"city": "Caldas"}, 
    {"city": "Paispamba"}, 
    {"city": "Gámeza"}, 
    {"city": "Bochalema"}, 
    {"city": "San Sebastián"}, 
    {"city": "Gómez Plata"}, 
    {"city": "Hobo"}, 
    {"city": "Nariño"}, 
    {"city": "San Andrés"}, 
    {"city": "Policarpa"}, 
    {"city": "El Molino"}, 
    {"city": "Giraldo"}, 
    {"city": "Santiago"}, 
    {"city": "Tangua"}, 
    {"city": "Miraflores"}, 
    {"city": "Puerto Salgar"}, 
    {"city": "Confines"}, 
    {"city": "Cajamarca"}, 
    {"city": "Gramalote"}, 
    {"city": "San Miguel de Sema"}, 
    {"city": "Corrales"}, 
    {"city": "Herrán"}, 
    {"city": "Íquira"}, 
    {"city": "Bituima"}, 
    {"city": "Guayatá"}, 
    {"city": "Colón"}, 
    {"city": "Vergara"}, 
    {"city": "Zambrano"}, 
    {"city": "Sabanalarga"}, 
    {"city": "Lourdes"}, 
    {"city": "Villahermosa"}, 
    {"city": "La Palma"}, 
    {"city": "San Martín de Loba"}, 
    {"city": "Alejandría"}, 
    {"city": "Ortega"}, 
    {"city": "Gama"}, 
    {"city": "Paz de Río"}, 
    {"city": "La Playa"}, 
    {"city": "Valle de San Juan"}, 
    {"city": "Puerto Nare"}, 
    {"city": "San Antonio"}, 
    {"city": "Algarrobo"}, 
    {"city": "Anzá"}, 
    {"city": "Pachavita"}, 
    {"city": "Agrado"}, 
    {"city": "Victoria"}, 
    {"city": "Coconuco"}, 
    {"city": "Yaguará"}, 
    {"city": "Santa Rita"}, 
    {"city": "Potosí"}, 
    {"city": "Santa María"}, 
    {"city": "El Peñón"}, 
    {"city": "Tamalameque"}, 
    {"city": "El Dovio"}, 
    {"city": "Supatá"}, 
    {"city": "Samaná"}, 
    {"city": "San Calixto"}, 
    {"city": "Versalles"}, 
    {"city": "Jesús María"}, 
    {"city": "Guapotá"}, 
    {"city": "Génova"}, 
    {"city": "Cértegui"}, 
    {"city": "Suárez"}, 
    {"city": "Berbeo"}, 
    {"city": "El Dorado"}, 
    {"city": "Salahonda"}, 
    {"city": "Pamplonita"}, 
    {"city": "La Tola"}, 
    {"city": "San Andrés"}, 
    {"city": "Villagómez"}, 
    {"city": "Cumaral"}, 
    {"city": "Machetá"}, 
    {"city": "San José de la Montaña"}, 
    {"city": "Jericó"}, 
    {"city": "San Juan de Rioseco"}, 
    {"city": "Guadalupe"}, 
    {"city": "Norcasia"}, 
    {"city": "Manta"}, 
    {"city": "Aguada"}, 
    {"city": "Carmen de Carupa"}, 
    {"city": "Venecia"}, 
    {"city": "Astrea"}, 
    {"city": "Paime"}, 
    {"city": "Carolina"}, 
    {"city": "San Miguel"}, 
    {"city": "Briceño"}, 
    {"city": "Mistrató"}, 
    {"city": "Zaragoza"}, 
    {"city": "Mercaderes"}, 
    {"city": "Ábrego"}, 
    {"city": "Sotaquirá"}, 
    {"city": "Sucre"}, 
    {"city": "Pijiño del Carmen"}, 
    {"city": "El Copey"}, 
    {"city": "El Carmen de Chucurí"}, 
    {"city": "Jordán"}, 
    {"city": "Suárez"}, 
    {"city": "Belmira"}, 
    {"city": "San Carlos"}, 
    {"city": "El Peñón"}, 
    {"city": "Peque"}, 
    {"city": "Beltrán"}, 
    {"city": "San Bernardo"}, 
    {"city": "Restrepo"}, 
    {"city": "Morelia"}, 
    {"city": "Saladoblanco"}, 
    {"city": "Macanal"}, 
    {"city": "Monterrey"}, 
    {"city": "Contratación"}, 
    {"city": "Tello"}, 
    {"city": "Santa Isabel"}, 
    {"city": "San Luis"}, 
    {"city": "Tesalia"}, 
    {"city": "Topaipí"}, 
    {"city": "Caparrapí"}, 
    {"city": "Punta de Piedras"}, 
    {"city": "Herveo"}, 
    {"city": "Hacarí"}, 
    {"city": "Altamira"}, 
    {"city": "Andagoya"}, 
    {"city": "La Llanada"}, 
    {"city": "Fuente de Oro"}, 
    {"city": "Yuto"}, 
    {"city": "Charta"}, 
    {"city": "Buriticá"}, 
    {"city": "Molagavita"}, 
    {"city": "Coper"}, 
    {"city": "Maceo"}, 
    {"city": "Pijao"}, 
    {"city": "Caracolí"}, 
    {"city": "Puerres"}, 
    {"city": "Mutiscua"}, 
    {"city": "Fómeque"}, 
    {"city": "Guaca"}, 
    {"city": "Ubalá"}, 
    {"city": "Castilla La Nueva"}, 
    {"city": "Otanche"}, 
    {"city": "San Francisco"}, 
    {"city": "San Diego"}, 
    {"city": "Mosquera"}, 
    {"city": "Vegachí"}, 
    {"city": "Yalí"}, 
    {"city": "Betéitiva"}, 
    {"city": "El Guamo"}, 
    {"city": "Cucutilla"}, 
    {"city": "Darién"}, 
    {"city": "La Paz"}, 
    {"city": "Prado"}, 
    {"city": "Morales"}, 
    {"city": "Guayabetal"}, 
    {"city": "Bolívar"}, 
    {"city": "San Martín"}, 
    {"city": "Managrú"}, 
    {"city": "El Rosario"}, 
    {"city": "Paicol"}, 
    {"city": "Durania"}, 
    {"city": "Pueblo Rico"}, 
    {"city": "Chaguaní"}, 
    {"city": "Macaravita"}, 
    {"city": "Cunday"}, 
    {"city": "San Cayetano"}, 
    {"city": "Cáchira"}, 
    {"city": "La Paz"}, 
    {"city": "Chiriguaná"}, 
    {"city": "El Tambo"}, 
    {"city": "Río Viejo"}, 
    {"city": "La Esperanza"}, 
    {"city": "Chima"}, 
    {"city": "Carcasí"}, 
    {"city": "Zetaquira"}, 
    {"city": "Puerto Caicedo"}, 
    {"city": "San Carlos de Guaroa"}, 
    {"city": "Arboledas"}, 
    {"city": "Frontino"}, 
    {"city": "Rondón"}, 
    {"city": "Rionegro"}, 
    {"city": "Piedras"}, 
    {"city": "San Joaquín"}, 
    {"city": "Sucre"}, 
    {"city": "Salazar"}, 
    {"city": "Teruel"}, 
    {"city": "La Gloria"}, 
    {"city": "Curillo"}, 
    {"city": "Ricaurte"}, 
    {"city": "Guamal"}, 
    {"city": "Yacopí"}, 
    {"city": "Bucarasica"}, 
    {"city": "Concepción"}, 
    {"city": "Chámeza"}, 
    {"city": "Beté"}, 
    {"city": "Gachalá"}, 
    {"city": "Cerrito"}, 
    {"city": "Santiago"}, 
    {"city": "Paimadó"}, 
    {"city": "Payán"}, 
    {"city": "Lloró"}, 
    {"city": "Convención"}, 
    {"city": "Unguía"}, 
    {"city": "Hato"}, 
    {"city": "San Ángel"}, 
    {"city": "Silos"}, 
    {"city": "Cácota"}, 
    {"city": "Villavieja"}, 
    {"city": "Piedrancha"}, 
    {"city": "Chivor"}, 
    {"city": "Pulí"}, 
    {"city": "Santa María"}, 
    {"city": "Acandí"}, 
    {"city": "Villa Caro"}, 
    {"city": "Ituango"}, 
    {"city": "Barbacoas"}, 
    {"city": "Remolino"}, 
    {"city": "Cantagallo"}, 
    {"city": "Mongua"}, 
    {"city": "Dolores"}, 
    {"city": "Santa Bárbara"}, 
    {"city": "Baraya"}, 
    {"city": "Bagadó"}, 
    {"city": "Campohermoso"}, 
    {"city": "Solita"}, 
    {"city": "Iscuandé"}, 
    {"city": "San José del Fragua"}, 
    {"city": "Betulia"}, 
    {"city": "Murillo"}, 
    {"city": "Socotá"}, 
    {"city": "Pore"}, 
    {"city": "San Luis de Gaceno"}, 
    {"city": "Becerril"}, 
    {"city": "Toledo"}, 
    {"city": "Mutis"}, 
    {"city": "Abriaquí"}, 
    {"city": "Cabrera"}, 
    {"city": "Belén de los Andaquíes"}, 
    {"city": "Villarrica"}, 
    {"city": "Alpujarra"}, 
    {"city": "Bolívar"}, 
    {"city": "Puerto Meluk"}, 
    {"city": "Albania"}, 
    {"city": "Valparaíso"}, 
    {"city": "Yondó"}, 
    {"city": "Santa Helena del Opón"}, 
    {"city": "El Guacamayo"}, 
    {"city": "Onzaga"}, 
    {"city": "Barranca de Upía"}, 
    {"city": "Funes"}, 
    {"city": "Gámbita"}, 
    {"city": "San Juanito"}, 
    {"city": "Suratá"}, 
    {"city": "Chitagá"}, 
    {"city": "Lejanías"}, 
    {"city": "El Castillo"}, 
    {"city": "Marulanda"}, 
    {"city": "El Carmen"}, 
    {"city": "Nunchía"}, 
    {"city": "La Salina"}, 
    {"city": "Gutiérrez"}, 
    {"city": "Piamonte"}, 
    {"city": "Nóvita"}, 
    {"city": "San Juan de Arama"}, 
    {"city": "Páez"}, 
    {"city": "Colombia"}, 
    {"city": "Milán"}, 
    {"city": "Támara"}, 
    {"city": "Trinidad"}, 
    {"city": "El Calvario"}, 
    {"city": "Roncesvalles"}, 
    {"city": "Paya"}, 
    {"city": "Pizarro"}, 
    {"city": "Puerto Rico"}, 
    {"city": "Sabanalarga"}, 
    {"city": "Cubarral"}, 
    {"city": "Cabuyaro"}, 
    {"city": "Santa Genoveva de Docordó"}, 
    {"city": "Mesetas"}, 
    {"city": "Vigía del Fuerte"}, 
    {"city": "Puerto Lleras"}, 
    {"city": "Mapiripán"}, 
    {"city": "Sácama"}, 
    {"city": "Maní"}, 
    {"city": "Murindó"}, 
    {"city": "Santa Rosa"}, 
    {"city": "Sipí"}, 
    {"city": "Hato Corozal"}, 
    {"city": "Bellavista"}, 
    {"city": "Pisba"}, 
    {"city": "San José del Palmar"}, 
    {"city": "Curbaradó"}, 
    {"city": "Puerto Leguízamo"}, 
    {"city": "Puerto Gaitán"}, 
    {"city": "Miraflores"}, 
    {"city": "Carurú"}, 
    {"city": "Calamar"}, 
    {"city": "Taraira"}, 
    {"city": "San José de Uré"},
] 

import React from "react";
import { useState } from "react";
import Select from "react-select";
import axios from 'axios';

const SuppliersCiudad = () => {
    
    const [ selectCiudad, setSelectCiudad] = useState();
    
    const selectChangeCiudad = ( {value} ) =>{
        setSelectCiudad(value);

    }
    return (
        <section>
                <p > {/* {selectCiudad} */}</p>
                <Select 
                    defaultValue= {{label: 'Ciudad', value: 'Ciudad'}}
                    options = {suppliersCiudad.map(sup => ({label: sup.city, value: sup.id}))}
                    onChange = {selectChangeCiudad}
                />
        </section>    
    )
}

export default SuppliersCiudad;